server:
  port: 8082
spring:
  application:
    name: Reward Service
  datasource:
    url: jdbc:postgresql://postgresql:5432/cofeappdb
    username: myuser
    password: mypass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql